# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_win0(object):
    def setupUi(self, win0):
        win0.setObjectName("win0")
        win0.resize(1171, 854)
        win0.setStyleSheet("background-color: rgba(29, 29, 29);\n"
"color: rgb(171, 171, 171);")
        self.centralwidget = QtWidgets.QWidget(win0)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(3, 9, 1106, 788))
        self.tabs.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.table1 = QtWidgets.QTableWidget(self.tab1)
        self.table1.setGeometry(QtCore.QRect(24, 20, 440, 713))
        self.table1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table1.setStyleSheet("background-color: rgba(100, 100, 100, 100);\n"
"border-color: rgb(47, 47, 47);\n"
"gridline-color: rgb(255, 255, 255);\n"
"color: rgb(100, 100, 100);\n"
"gridline-color: rgb(40, 40, 40);")
        self.table1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table1.setRowCount(100)
        self.table1.setColumnCount(4)
        self.table1.setObjectName("table1")
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)
        self.table1.horizontalHeader().setDefaultSectionSize(100)
        self.table1.verticalHeader().setDefaultSectionSize(20)
        self.frame = QtWidgets.QFrame(self.tab1)
        self.frame.setGeometry(QtCore.QRect(479, 20, 589, 305))
        self.frame.setStyleSheet("border-color: rgb(65, 65, 65);\n"
"gridline-color: rgb(65, 65, 65);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.from_label = QtWidgets.QLabel(self.frame)
        self.from_label.setGeometry(QtCore.QRect(224, 9, 26, 16))
        self.from_label.setObjectName("from_label")
        self.min_label_2 = QtWidgets.QLabel(self.frame)
        self.min_label_2.setGeometry(QtCore.QRect(251, 206, 19, 16))
        self.min_label_2.setObjectName("min_label_2")
        self.spin_hours_2 = QtWidgets.QSpinBox(self.frame)
        self.spin_hours_2.setGeometry(QtCore.QRect(203, 226, 36, 22))
        self.spin_hours_2.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_hours_2.setObjectName("spin_hours_2")
        self.date_label = QtWidgets.QLabel(self.frame)
        self.date_label.setGeometry(QtCore.QRect(24, 31, 28, 14))
        self.date_label.setObjectName("date_label")
        self.hours_label_3 = QtWidgets.QLabel(self.frame)
        self.hours_label_3.setGeometry(QtCore.QRect(340, 207, 34, 16))
        self.hours_label_3.setObjectName("hours_label_3")
        self.button_quit_ops = QtWidgets.QPushButton(self.frame)
        self.button_quit_ops.setGeometry(QtCore.QRect(290, 145, 35, 23))
        self.button_quit_ops.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.button_quit_ops.setObjectName("button_quit_ops")
        self.button_date_to = QtWidgets.QToolButton(self.frame)
        self.button_date_to.setGeometry(QtCore.QRect(359, 28, 24, 20))
        self.button_date_to.setStyleSheet("background-color: rgb(65, 65, 65);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/calendar2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../Icons/calendar2 (Pressed).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../Icons/calendar2 (Pressed).jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../Icons/calendar2 (Pressed).jpg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.button_date_to.setIcon(icon)
        self.button_date_to.setIconSize(QtCore.QSize(18, 18))
        self.button_date_to.setObjectName("button_date_to")
        self.button_date_from = QtWidgets.QToolButton(self.frame)
        self.button_date_from.setGeometry(QtCore.QRect(266, 28, 24, 20))
        self.button_date_from.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.button_date_from.setIcon(icon)
        self.button_date_from.setIconSize(QtCore.QSize(18, 18))
        self.button_date_from.setObjectName("button_date_from")
        self.min_label_3 = QtWidgets.QLabel(self.frame)
        self.min_label_3.setGeometry(QtCore.QRect(384, 207, 19, 16))
        self.min_label_3.setObjectName("min_label_3")
        self.combo_box_ops_date = QtWidgets.QComboBox(self.frame)
        self.combo_box_ops_date.setGeometry(QtCore.QRect(56, 28, 135, 20))
        self.combo_box_ops_date.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.combo_box_ops_date.setObjectName("combo_box_ops_date")
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setGeometry(QtCore.QRect(22, 227, 28, 16))
        self.time_label.setObjectName("time_label")
        self.spin_min_3 = QtWidgets.QSpinBox(self.frame)
        self.spin_min_3.setGeometry(QtCore.QRect(374, 227, 36, 22))
        self.spin_min_3.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_min_3.setObjectName("spin_min_3")
        self.button_add_acts = QtWidgets.QPushButton(self.frame)
        self.button_add_acts.setGeometry(QtCore.QRect(290, 116, 35, 23))
        self.button_add_acts.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.button_add_acts.setObjectName("button_add_acts")
        self.spin_sec_2 = QtWidgets.QSpinBox(self.frame)
        self.spin_sec_2.setGeometry(QtCore.QRect(279, 226, 36, 22))
        self.spin_sec_2.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_sec_2.setObjectName("spin_sec_2")
        self.all_acts_list = QtWidgets.QListView(self.frame)
        self.all_acts_list.setGeometry(QtCore.QRect(56, 83, 220, 117))
        self.all_acts_list.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.all_acts_list.setObjectName("all_acts_list")
        self.activity_label = QtWidgets.QLabel(self.frame)
        self.activity_label.setGeometry(QtCore.QRect(12, 78, 42, 16))
        self.activity_label.setObjectName("activity_label")
        self.to_label = QtWidgets.QLabel(self.frame)
        self.to_label.setGeometry(QtCore.QRect(322, 9, 17, 16))
        self.to_label.setObjectName("to_label")
        self.date_to = QtWidgets.QDateEdit(self.frame)
        self.date_to.setGeometry(QtCore.QRect(294, 27, 65, 20))
        self.date_to.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.date_to.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_to.setKeyboardTracking(True)
        self.date_to.setObjectName("date_to")
        self.sec_label_2 = QtWidgets.QLabel(self.frame)
        self.sec_label_2.setGeometry(QtCore.QRect(288, 207, 22, 16))
        self.sec_label_2.setObjectName("sec_label_2")
        self.spin_hours_3 = QtWidgets.QSpinBox(self.frame)
        self.spin_hours_3.setGeometry(QtCore.QRect(336, 227, 36, 22))
        self.spin_hours_3.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_hours_3.setObjectName("spin_hours_3")
        self.spin_sec_3 = QtWidgets.QSpinBox(self.frame)
        self.spin_sec_3.setGeometry(QtCore.QRect(412, 227, 36, 22))
        self.spin_sec_3.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_sec_3.setObjectName("spin_sec_3")
        self.spin_min_2 = QtWidgets.QSpinBox(self.frame)
        self.spin_min_2.setGeometry(QtCore.QRect(241, 226, 36, 22))
        self.spin_min_2.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_min_2.setObjectName("spin_min_2")
        self.activities_show_label = QtWidgets.QLabel(self.frame)
        self.activities_show_label.setGeometry(QtCore.QRect(406, 65, 93, 16))
        self.activities_show_label.setObjectName("activities_show_label")
        self.date_from = QtWidgets.QDateEdit(self.frame)
        self.date_from.setGeometry(QtCore.QRect(202, 27, 65, 21))
        self.date_from.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.date_from.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_from.setKeyboardTracking(True)
        self.date_from.setObjectName("date_from")
        self.combo_box_ops_time = QtWidgets.QComboBox(self.frame)
        self.combo_box_ops_time.setGeometry(QtCore.QRect(55, 227, 135, 20))
        self.combo_box_ops_time.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.combo_box_ops_time.setObjectName("combo_box_ops_time")
        self.hours_label_2 = QtWidgets.QLabel(self.frame)
        self.hours_label_2.setGeometry(QtCore.QRect(207, 206, 34, 16))
        self.hours_label_2.setObjectName("hours_label_2")
        self.sec_label_3 = QtWidgets.QLabel(self.frame)
        self.sec_label_3.setGeometry(QtCore.QRect(421, 208, 22, 16))
        self.sec_label_3.setObjectName("sec_label_3")
        self.all_activities_label = QtWidgets.QLabel(self.frame)
        self.all_activities_label.setGeometry(QtCore.QRect(137, 65, 60, 16))
        self.all_activities_label.setObjectName("all_activities_label")
        self.default_button = QtWidgets.QPushButton(self.frame)
        self.default_button.setGeometry(QtCore.QRect(21, 265, 75, 23))
        self.default_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.default_button.setObjectName("default_button")
        self.activities_show_list = QtWidgets.QListView(self.frame)
        self.activities_show_list.setGeometry(QtCore.QRect(336, 83, 220, 117))
        self.activities_show_list.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.activities_show_list.setObjectName("activities_show_list")
        self.frame_2 = QtWidgets.QFrame(self.tab1)
        self.frame_2.setGeometry(QtCore.QRect(480, 348, 589, 95))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.time_label_2 = QtWidgets.QLabel(self.frame_2)
        self.time_label_2.setGeometry(QtCore.QRect(509, 9, 24, 16))
        self.time_label_2.setObjectName("time_label_2")
        self.spin_hours = QtWidgets.QSpinBox(self.frame_2)
        self.spin_hours.setGeometry(QtCore.QRect(465, 45, 36, 22))
        self.spin_hours.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_hours.setObjectName("spin_hours")
        self.sec_label = QtWidgets.QLabel(self.frame_2)
        self.sec_label.setGeometry(QtCore.QRect(550, 26, 22, 16))
        self.sec_label.setObjectName("sec_label")
        self.activity_label_2 = QtWidgets.QLabel(self.frame_2)
        self.activity_label_2.setGeometry(QtCore.QRect(160, 12, 37, 17))
        self.activity_label_2.setObjectName("activity_label_2")
        self.date_label_2 = QtWidgets.QLabel(self.frame_2)
        self.date_label_2.setGeometry(QtCore.QRect(31, 13, 25, 16))
        self.date_label_2.setObjectName("date_label_2")
        self.spin_min = QtWidgets.QSpinBox(self.frame_2)
        self.spin_min.setGeometry(QtCore.QRect(503, 45, 36, 22))
        self.spin_min.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_min.setObjectName("spin_min")
        self.new_button = QtWidgets.QPushButton(self.frame_2)
        self.new_button.setGeometry(QtCore.QRect(7, 64, 33, 23))
        self.new_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.new_button.setObjectName("new_button")
        self.spin_sec = QtWidgets.QSpinBox(self.frame_2)
        self.spin_sec.setGeometry(QtCore.QRect(541, 45, 36, 22))
        self.spin_sec.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.spin_sec.setObjectName("spin_sec")
        self.description_label = QtWidgets.QLabel(self.frame_2)
        self.description_label.setGeometry(QtCore.QRect(330, 10, 54, 16))
        self.description_label.setObjectName("description_label")
        self.hours_label = QtWidgets.QLabel(self.frame_2)
        self.hours_label.setGeometry(QtCore.QRect(469, 25, 34, 16))
        self.hours_label.setObjectName("hours_label")
        self.min_label = QtWidgets.QLabel(self.frame_2)
        self.min_label.setGeometry(QtCore.QRect(513, 25, 19, 16))
        self.min_label.setObjectName("min_label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(103, 32, 141, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineEdit.setObjectName("lineEdit")
        self.text_description = QtWidgets.QPlainTextEdit(self.frame_2)
        self.text_description.setGeometry(QtCore.QRect(255, 30, 202, 56))
        self.text_description.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.text_description.setObjectName("text_description")
        self.button_date_selected = QtWidgets.QToolButton(self.frame_2)
        self.button_date_selected.setGeometry(QtCore.QRect(72, 31, 24, 20))
        self.button_date_selected.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.button_date_selected.setIcon(icon)
        self.button_date_selected.setIconSize(QtCore.QSize(18, 18))
        self.button_date_selected.setObjectName("button_date_selected")
        self.date_selected = QtWidgets.QDateEdit(self.frame_2)
        self.date_selected.setGeometry(QtCore.QRect(8, 30, 65, 21))
        self.date_selected.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.date_selected.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_selected.setKeyboardTracking(True)
        self.date_selected.setObjectName("date_selected")
        self.update_button = QtWidgets.QPushButton(self.frame_2)
        self.update_button.setGeometry(QtCore.QRect(49, 64, 59, 23))
        self.update_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.update_button.setObjectName("update_button")
        self.unselect_button = QtWidgets.QPushButton(self.frame_2)
        self.unselect_button.setGeometry(QtCore.QRect(117, 64, 59, 23))
        self.unselect_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.unselect_button.setObjectName("unselect_button")
        self.delete_button = QtWidgets.QPushButton(self.frame_2)
        self.delete_button.setGeometry(QtCore.QRect(185, 64, 59, 23))
        self.delete_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.delete_button.setObjectName("delete_button")
        self.tabs.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 20, 1060, 630))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graph_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")
        self.tabs.addTab(self.tab2, "")
        win0.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(win0)
        self.statusbar.setObjectName("statusbar")
        win0.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(win0)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1171, 21))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        win0.setMenuBar(self.menubar)
        self.new_workspace_menu = QtWidgets.QAction(win0)
        self.new_workspace_menu.setObjectName("new_workspace_menu")
        self.open_workspace_menu = QtWidgets.QAction(win0)
        self.open_workspace_menu.setObjectName("open_workspace_menu")
        self.save_workspace_menu = QtWidgets.QAction(win0)
        self.save_workspace_menu.setObjectName("save_workspace_menu")
        self.saveas_workspace_menu = QtWidgets.QAction(win0)
        self.saveas_workspace_menu.setObjectName("saveas_workspace_menu")
        self.import_menu = QtWidgets.QAction(win0)
        self.import_menu.setObjectName("import_menu")
        self.line_graphic = QtWidgets.QAction(win0)
        self.line_graphic.setObjectName("line_graphic")
        self.menuNew.addAction(self.new_workspace_menu)
        self.menuNew.addAction(self.open_workspace_menu)
        self.menuNew.addAction(self.save_workspace_menu)
        self.menuNew.addAction(self.saveas_workspace_menu)
        self.menuImport.addAction(self.import_menu)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(win0)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(win0)

    def retranslateUi(self, win0):
        _translate = QtCore.QCoreApplication.translate
        win0.setWindowTitle(_translate("win0", "Time Visualizer"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("win0", "Date"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("win0", "Activity"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("win0", "Details"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("win0", "Time"))
        self.from_label.setText(_translate("win0", "From"))
        self.min_label_2.setText(_translate("win0", "Min"))
        self.date_label.setText(_translate("win0", "Date:"))
        self.hours_label_3.setText(_translate("win0", "Hours"))
        self.button_quit_ops.setText(_translate("win0", "<-"))
        self.button_date_to.setText(_translate("win0", "..."))
        self.button_date_from.setText(_translate("win0", "..."))
        self.min_label_3.setText(_translate("win0", "Min"))
        self.time_label.setText(_translate("win0", "Time:"))
        self.button_add_acts.setText(_translate("win0", "->"))
        self.activity_label.setText(_translate("win0", "Activity:"))
        self.to_label.setText(_translate("win0", "To"))
        self.sec_label_2.setText(_translate("win0", "Sec"))
        self.activities_show_label.setText(_translate("win0", "Activities To Show"))
        self.hours_label_2.setText(_translate("win0", "Hours"))
        self.sec_label_3.setText(_translate("win0", "Sec"))
        self.all_activities_label.setText(_translate("win0", "All Activities"))
        self.default_button.setText(_translate("win0", "Default"))
        self.time_label_2.setText(_translate("win0", "Time"))
        self.sec_label.setText(_translate("win0", "Sec"))
        self.activity_label_2.setText(_translate("win0", "Activity"))
        self.date_label_2.setText(_translate("win0", "Date"))
        self.new_button.setText(_translate("win0", "New"))
        self.description_label.setText(_translate("win0", "Description"))
        self.hours_label.setText(_translate("win0", "Hours"))
        self.min_label.setText(_translate("win0", "Min"))
        self.button_date_selected.setText(_translate("win0", "..."))
        self.update_button.setText(_translate("win0", "Update"))
        self.unselect_button.setText(_translate("win0", "Unselect"))
        self.delete_button.setText(_translate("win0", "Delete"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1), _translate("win0", "Selected Data"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), _translate("win0", "+"))
        self.menuNew.setTitle(_translate("win0", "New"))
        self.menuImport.setTitle(_translate("win0", "Import"))
        self.new_workspace_menu.setText(_translate("win0", "New Workspace"))
        self.open_workspace_menu.setText(_translate("win0", "Open Workspace"))
        self.save_workspace_menu.setText(_translate("win0", "Save Workspace"))
        self.saveas_workspace_menu.setText(_translate("win0", "Save As Workspace"))
        self.import_menu.setText(_translate("win0", "Import From CSV"))
        self.line_graphic.setText(_translate("win0", "Line Graphic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win0 = QtWidgets.QMainWindow()
    ui = Ui_win0()
    ui.setupUi(win0)
    win0.show()
    sys.exit(app.exec_())

