# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_win1(object):
    def setupUi(self, win1):
        win1.setObjectName("win1")
        win1.setEnabled(True)
        win1.resize(376, 290)
        win1.setTabletTracking(False)
        win1.setFocusPolicy(QtCore.Qt.StrongFocus)
        win1.setStyleSheet("background-color: rgb(29, 29, 29);\n"
"color: rgb(171, 171, 171);")
        win1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        win1.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(win1)
        self.centralwidget.setObjectName("centralwidget")
        self.chackbox_csv = QtWidgets.QCheckBox(self.centralwidget)
        self.chackbox_csv.setEnabled(True)
        self.chackbox_csv.setGeometry(QtCore.QRect(25, 21, 13, 13))
        self.chackbox_csv.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.chackbox_csv.setText("")
        self.chackbox_csv.setObjectName("chackbox_csv")
        self.lineedit_csv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_csv.setEnabled(True)
        self.lineedit_csv.setGeometry(QtCore.QRect(100, 18, 239, 18))
        self.lineedit_csv.setMouseTracking(True)
        self.lineedit_csv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineedit_csv.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineedit_csv.setStatusTip("")
        self.lineedit_csv.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_csv.setFrame(True)
        self.lineedit_csv.setDragEnabled(False)
        self.lineedit_csv.setObjectName("lineedit_csv")
        self.examin_button = QtWidgets.QPushButton(self.centralwidget)
        self.examin_button.setEnabled(True)
        self.examin_button.setGeometry(QtCore.QRect(270, 42, 70, 22))
        self.examin_button.setStatusTip("")
        self.examin_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.examin_button.setCheckable(False)
        self.examin_button.setAutoRepeat(False)
        self.examin_button.setDefault(False)
        self.examin_button.setObjectName("examin_button")
        self.lineedit_service = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_service.setEnabled(False)
        self.lineedit_service.setGeometry(QtCore.QRect(101, 89, 237, 17))
        self.lineedit_service.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineedit_service.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_service.setObjectName("lineedit_service")
        self.label_service = QtWidgets.QLabel(self.centralwidget)
        self.label_service.setEnabled(True)
        self.label_service.setGeometry(QtCore.QRect(56, 88, 39, 16))
        self.label_service.setObjectName("label_service")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(68, 115, 27, 16))
        self.label_user.setObjectName("label_user")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(47, 145, 47, 13))
        self.label_password.setObjectName("label_password")
        self.lineedit_user = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_user.setEnabled(False)
        self.lineedit_user.setGeometry(QtCore.QRect(101, 117, 237, 17))
        self.lineedit_user.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_user.setObjectName("lineedit_user")
        self.lineedit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_pass.setEnabled(False)
        self.lineedit_pass.setGeometry(QtCore.QRect(101, 145, 237, 17))
        self.lineedit_pass.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_pass.setObjectName("lineedit_pass")
        self.lineedit_db_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_db_name.setEnabled(False)
        self.lineedit_db_name.setGeometry(QtCore.QRect(101, 173, 237, 17))
        self.lineedit_db_name.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_db_name.setObjectName("lineedit_db_name")
        self.label_database_name = QtWidgets.QLabel(self.centralwidget)
        self.label_database_name.setGeometry(QtCore.QRect(16, 172, 84, 16))
        self.label_database_name.setObjectName("label_database_name")
        self.lineedit_table_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_table_name.setEnabled(False)
        self.lineedit_table_name.setGeometry(QtCore.QRect(101, 201, 237, 17))
        self.lineedit_table_name.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.lineedit_table_name.setObjectName("lineedit_table_name")
        self.label_table_name = QtWidgets.QLabel(self.centralwidget)
        self.label_table_name.setGeometry(QtCore.QRect(36, 200, 63, 16))
        self.label_table_name.setObjectName("label_table_name")
        self.accept_button = QtWidgets.QPushButton(self.centralwidget)
        self.accept_button.setEnabled(False)
        self.accept_button.setGeometry(QtCore.QRect(110, 244, 75, 23))
        self.accept_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.accept_button.setObjectName("accept_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setEnabled(False)
        self.cancel_button.setGeometry(QtCore.QRect(202, 244, 75, 23))
        self.cancel_button.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.cancel_button.setObjectName("cancel_button")
        self.chackbox_database = QtWidgets.QCheckBox(self.centralwidget)
        self.chackbox_database.setEnabled(True)
        self.chackbox_database.setGeometry(QtCore.QRect(25, 65, 13, 13))
        self.chackbox_database.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.chackbox_database.setText("")
        self.chackbox_database.setObjectName("chackbox_database")
        self.label_csv = QtWidgets.QLabel(self.centralwidget)
        self.label_csv.setGeometry(QtCore.QRect(49, 20, 47, 13))
        self.label_csv.setObjectName("label_csv")
        self.label_database = QtWidgets.QLabel(self.centralwidget)
        self.label_database.setGeometry(QtCore.QRect(45, 64, 47, 13))
        self.label_database.setObjectName("label_database")
        win1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(win1)
        self.statusbar.setObjectName("statusbar")
        win1.setStatusBar(self.statusbar)

        self.retranslateUi(win1)
        QtCore.QMetaObject.connectSlotsByName(win1)

    def retranslateUi(self, win1):
        _translate = QtCore.QCoreApplication.translate
        win1.setWindowTitle(_translate("win1", "Configurate Workspace"))
        self.examin_button.setText(_translate("win1", "Examin"))
        self.label_service.setText(_translate("win1", "Service:"))
        self.label_user.setText(_translate("win1", "User:"))
        self.label_password.setText(_translate("win1", "Password:"))
        self.label_database_name.setText(_translate("win1", "Database name:"))
        self.label_table_name.setText(_translate("win1", "Table name:"))
        self.accept_button.setText(_translate("win1", "Accept"))
        self.cancel_button.setText(_translate("win1", "Cancel"))
        self.label_csv.setText(_translate("win1", "CSV"))
        self.label_database.setText(_translate("win1", "Database"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     win1 = QtWidgets.QMainWindow()
#     ui = Ui_win1()
#     ui.setupUi(win1)
#     win1.show()
#     sys.exit(app.exec_())

